"wheat"                = "#F5DEB3"
"peru"                 = "#CD853F"
"slategray"            = "#708090"
"gold"                 = "#FFD700"
"tan"                  = "#D2B48C"
"burlywood"            = "#DEB887"
"blanchedalmond"       = "#FFEBCD"
"palevioletred"        = "#DB7093"
"darkturquoise"        = "#00CED1"
"bisque"               = "#FFE4C4"
"snow"                 = "#FFFAFA"
"ivory"                = "#FFFFF0"
"skyblue"              = "#87CEEB"
"coral"                = "#FF7F50"
"maroon"               = "#800000"
"chocolate"            = "#D2691E"
"cornsilk"             = "#FFF8DC"
"whitesmoke"           = "#F5F5F5"
"rosybrown"            = "#BC8F8F"
"lavenderblush"        = "#FFF0F5"
"lightslategray"       = "#778899"
"yellow"               = "#FFFF00"
"mistyrose"            = "#FFE4E1"
"deeppink"             = "#FF1493"
"royalblue"            = "#4169E1"
"mediumblue"           = "#0000CD"
"lightseagreen"        = "#20B2AA"
"mediumturquoise"      = "#48D1CC"
"navy"                 = "#000080"
"blueviolet"           = "#8A2BE2"
"saddlebrown"          = "#8B4513"
"darkgoldenrod"        = "#B8860B"
"lemonchiffon"         = "#FFFACD"
"navajowhite"          = "#FFDEAD"
"salmon"               = "#FA8072"
"beige"                = "#F5F5DC"
"forestgreen"          = "#228B22"
"brown"                = "#A52A2A"
"lightskyblue"         = "#87CEFA"
"limegreen"            = "#32CD32"
"darkmagenta"          = "#8B008B"
"darkseagreen"         = "#8FBC8F"
"lightcoral"           = "#F08080"
"mediumvioletred"      = "#C71585"
"darkolivegreen"       = "#556B2F"
"lavender"             = "#E6E6FA"
"midnightblue"         = "#191970"
"turquoise"            = "#40E0D0"
"mediumaquamarine"     = "#66CDAA"
"cadetblue"            = "#5F9EA0"
"darkgray"             = "#A9A9A9"
"darkslateblue"        = "#483D8B"
"mediumspringgreen"    = "#00FA9A"
"lightgoldenrodyellow" = "#FAFAD2"
"olivedrab"            = "#6B8E23"
"thistle"              = "#D8BFD8"
"indianred"            = "#CD5C5C"
"gainsboro"            = "#DCDCDC"
"azure"                = "#F0FFFF"
"darkviolet"           = "#9400D3"
"mediumpurple"         = "#9370DB"
"lightcyan"            = "#E0FFFF"
"crimson"              = "#DC143C"
"sienna"               = "#A0522D"
"peachpuff"            = "#FFDAB9"
"mediumseagreen"       = "#3CB371"
"lightsalmon"          = "#FFA07A"
"sandybrown"           = "#F4A460"
"pink"                 = "#FFC0CB"
"lightsteelblue"       = "#B0C4DE"
"indigo"               = "#4B0082"
"oldlace"              = "#FDF5E6"
"lawngreen"            = "#7CFC00"
"darkgreen"            = "#006400"
"honeydew"             = "#F0FFF0"
"darkkhaki"            = "#BDB76B"
"mediumslateblue"      = "#7B68EE"
"deepskyblue"          = "#00BFFF"
"aqua (cyan)"          = "#00FFFF"
"ghostwhite"           = "#F8F8FF"
"green"                = "#008000"
"palegreen"            = "#98FB98"
"paleturquoise"        = "#AFEEEE"
"dodgerblue"           = "#1E90FF"
"silver"               = "#C0C0C0"
"linen"                = "#FAF0E6"
"lightgreen"           = "#90EE90"
"tomato"               = "#FF6347"
"darkslategray"        = "#2F4F4F"
"aquamarine"           = "#7FFFD4"
"gray"                 = "#808080"
"seagreen"             = "#2E8B57"
"dimgray"              = "#696969"
"darkred"              = "#8B0000"
"powderblue"           = "#B0E0E6"
"magenta (fuchsia)"    = "#FF00FF"
"palegoldenrod"        = "#EEE8AA"
"floralwhite"          = "#FFFAF0"
"goldenrod"            = "#DAA520"
"mintcream"            = "#F5FFFA"
"purple"               = "#800080"
"springgreen"          = "#00FF7F"
"orange"               = "#FFA500"
"blue"                 = "#0000FF"
"firebrick"            = "#B22222"
"darkcyan"             = "#008B8B"
"lightgray"            = "#D3D3D3"
"aliceblue"            = "#F0F8FF"
"olive"                = "#808000"
"violet"               = "#EE82EE"
"darkorange"           = "#FF8C00"
"lime"                 = "#00FF00"
"greenyellow"          = "#ADFF2F"
"lightpink"            = "#FFB6C1"
"slateblue"            = "#6A5ACD"
"white"                = "#FFFFFF"
"mediumorchid"         = "#BA55D3"
"papayawhip"           = "#FFEFD5"
"darksalmon"           = "#E9967A"
"moccasin"             = "#FFE4B5"
"rebeccapurple"        = "#663399"
"hotpink"              = "#FF69B4"
"khaki"                = "#F0E68C"
"antiquewhite"         = "#FAEBD7"
"red"                  = "#FF0000"
"plum"                 = "#DDA0DD"
"cornflowerblue"       = "#6495ED"
"darkblue"             = "#00008B"
"lightyellow"          = "#FFFFE0"
"orangered"            = "#FF4500"
"chartreuse"           = "#7FFF00"
"lightblue"            = "#ADD8E6"
"yellowgreen"          = "#9ACD32"
"darkorchid"           = "#9932CC"
"teal"                 = "#008080"
"steelblue"            = "#4682B4"
"seashell"             = "#FFF5EE"
"black"                = "#000000"
"orchid"               = "#DA70D6"
