# Pre-commit hooks configuration for pixelate
repos:
  # Run tests and local tools
  - repo: local
    hooks:
      - id: formatting
        name: formatting
        entry: make formatting
        types: [python]
        language: system