"purple" = "#9467BD"
"pink"   = "#E377C2"
"red"    = "#D62728"
"brown"  = "#8C564B"
"gray"   = "#7F7F7F"
"cyan"   = "#17BECF"
"orange" = "#FF7F0E"
"green"  = "#2CA02C"
"olive"  = "#BCBD22"
"blue"   = "#1F77B4"
