name: Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    name: linting, typing and security (Python 3.11)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python 3.11
      run: uv python install 3.11

    - name: Install dependencies
      shell: bash
      run: |
        make install-dev

    - name: Linting with ruff
      shell: bash
      run: |
        make linting

    - name: Type checking with mypy
      shell: bash
      run: |
        make typing

    - name: Security checking with bandit
      shell: bash
      run: |
        make security
