name: release

on:
  workflow_dispatch:

jobs:
  release:
    name: release (Python 3.11)
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python 3.11
      run: uv python install 3.11

    - name: Install dependencies
      shell: bash
      run: |
        make install
        uv run python -m pip install tomli

    - name: Get version from pyproject.toml
      id: get_version
      run: |
        echo "VERSION=$(python -c "
        import tomli
        with open('pyproject.toml', 'rb') as f:
            print(tomli.load(f)['project']['version'])
        ")" >> $GITHUB_OUTPUT

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ steps.get_version.outputs.VERSION }}
      run: |
        gh release create "v${VERSION}" \
          --title "Release v${VERSION}" \
          --notes-file <(envsubst < .github/RELEASE.md)
