name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        uv sync --all-groups --all-extras

    - name: Test with pytest
      shell: bash
      run: |
        make test-report

    - name: Test CLI functionality
      shell: bash
      run: |
        # Test CLI help
        uv run pixelate --help

        # Test with example file
        uv run pixelate examples/pixelate.md

        # Verify output was created
        ls -la examples/pixelate.png

        # Clean up
        rm examples/pixelate.png
